#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

export APACHE_RUN_DIR="/var/run/apache2"
mkdir -p $APACHE_RUN_DIR
chown www-data:www-data $APACHE_RUN_DIR

export APACHE_LOG_DIR="/var/log/apache2"
mkdir -p $APACHE_LOG_DIR
chown www-data:www-data $APACHE_LOG_DIR

export APACHE_LOCK_DIR="/var/lock/apache2"
mkdir -p $APACHE_LOCK_DIR
chown www-data:www-data $APACHE_LOCK_DIR

export APACHE_RUN_USER="www-data"
export APACHE_RUN_GROUP="www-data"
export APACHE_PID_FILE="/var/run/apache2/apache2.pid"


exec 2>&1
exec /usr/sbin/apache2 -DFOREGROUND
